name: "purgedups_splitfa"
description: Split fasta file by 'N's to aid in self alignment for duplicate purging
keywords:
  - split
  - assembly
  - duplicate
  - purging
tools:
  - "purgedups":
      description: "Purge_dups is a package used to purge haplotigs and overlaps in
        an assembly based on read depth"
      homepage: "https://github.com/dfguan/purge_dups"
      documentation: "https://github.com/dfguan/purge_dups"
      tool_dev_url: "https://github.com/dfguan/purge_dups"
      doi: "10.1093/bioinformatics/btaa025"
      licence: ["MIT"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - assembly:
        type: file
        description: Draft assembly file
        pattern: "*.fasta"
        ontologies: []
output:
  split_fasta:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.split.fasta.gz":
          type: file
          description: Fasta split by N's
          pattern: "*.fasta.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  versions_purgedups:
    - - ${task.process}:
          type: string
          description: The name of the process
      - purge_dups:
          type: string
          description: The name of the tool
      - 1.2.6:
          type: string
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - purge_dups:
          type: string
          description: The name of the tool
      - 1.2.6:
          type: string
          description: The expression to obtain the version of the tool
authors:
  - "@mahesh-panchal"
maintainers:
  - "@mahesh-panchal"
