name: "purgedups_pbcstat"
description: Create read depth histogram and base-level read depth for an assembly
  based on pacbio data
keywords:
  - sort
  - genome assembly
  - purge duplications
  - read depth
tools:
  - "purgedups":
      description: "Purge_dups is a package used to purge haplotigs and overlaps in
        an assembly based on read depth"
      homepage: "https://github.com/dfguan/purge_dups"
      documentation: "https://github.com/dfguan/purge_dups"
      tool_dev_url: "https://github.com/dfguan/purge_dups"
      doi: "10.1093/bioinformatics/btaa025"
      licence: ["MIT"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - paf_alignment:
        type: file
        description: PAF alignment file
        pattern: "*.paf"
        ontologies: []
output:
  stat:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.PB.stat":
          type: file
          description: PacBio Statistic file
          pattern: "*.PB.stat"
          ontologies: []
  basecov:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.PB.base.cov":
          type: file
          description: PacBio Base coverage file
          pattern: "*.PB.base.cov"
          ontologies: []
  versions_purgedups:
    - - ${task.process}:
          type: string
          description: The name of the process
      - purge_dups:
          type: string
          description: The name of the tool
      - 1.2.6:
          type: string
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - purge_dups:
          type: string
          description: The name of the tool
      - 1.2.6:
          type: string
          description: The expression to obtain the version of the tool
authors:
  - "@mahesh-panchal"
maintainers:
  - "@mahesh-panchal"
