# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "samtools_addreplacerg"
description: Adds or replaces read group (RG) tags in BAM/CRAM/SAM files
keywords:
  - addreplacerg
  - bam
  - sam
  - cram
tools:
  - "samtools":
      description: "Tools for dealing with SAM, BAM and CRAM files"
      homepage: "http://www.htslib.org"
      documentation: "https://www.htslib.org/doc/samtools-addreplacerg.html"
      tool_dev_url: "https://github.com/samtools/samtools"
      doi: "10.1093/bioinformatics/btp352"
      licence: ["MIT"]
      identifier: biotools:samtools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input:
        type: file
        description: BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies: []
    - index:
        type: file
        description: BAM/CRAM/SAM index file
        pattern: "*.{bai,csi,crai}"
        ontologies: []
    - read_group:
        type: string
        description: Read group line to add or replace
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'genome' ]
    - fasta:
        type: file
        description: Reference file the CRAM was created with (optional)
        pattern: "*.{fasta,fa}"
        ontologies: []
    - fai:
        type: file
        description: Index of the reference file the CRAM was created with (optional)
        pattern: "*.fai"
        ontologies: []
    - gzi:
        type: file
        description: Index of the compressed reference file the CRAM was created with
          (optional)
        pattern: "*.gzi"
        ontologies: []
output:
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "${prefix}.bam":
          type: file
          description: BAM file with updated RG tags
          pattern: "${prefix}.bam"
          ontologies: []
  cram:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "${prefix}.cram":
          type: file
          description: CRAM file with updated RG tags
          pattern: "${prefix}.cram"
          ontologies: []
  sam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "${prefix}.sam":
          type: file
          description: SAM file with updated RG tags
          pattern: "${prefix}.sam"
          ontologies: []
  bai:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "${prefix}.bam.bai":
          type: file
          description: BAM index file
          pattern: "${prefix}.bam.bai"
          ontologies: []
  csi:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "${prefix}.bam.csi":
          type: file
          description: BAM CSI index file
          pattern: "${prefix}.bam.csi"
          ontologies: []
  crai:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "${prefix}.cram.crai":
          type: file
          description: CRAM index file
          pattern: "${prefix}.cram.crai"
          ontologies: []
  versions_samtools:
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - samtools version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - samtools version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@sainsachiko"
maintainers:
  - "@sainsachiko"
