name: "purgedups_calcuts"
description: Calculate coverage cutoffs to determine when to purge duplicated
  sequence.
keywords:
  - coverage
  - cutoff
  - purge duplications
tools:
  - "purgedups":
      description: "Purge_dups is a package used to purge haplotigs and overlaps in
        an assembly based on read depth"
      homepage: "https://github.com/dfguan/purge_dups"
      documentation: "https://github.com/dfguan/purge_dups"
      tool_dev_url: "https://github.com/dfguan/purge_dups"
      doi: "10.1093/bioinformatics/btaa025"
      licence:
        - "MIT"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - stat:
        type: file
        description: Histogram of coverage
        pattern: "*.stat"
        ontologies: []
output:
  cutoff:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.cutoffs":
          type: file
          description: Cutoff file
          pattern: "*.cutoffs"
          ontologies: []
  log:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.calcuts.log":
          type: file
          description: Log file
          pattern: ".calcuts.log"
          ontologies: []
  versions_purgedups:
    - - ${task.process}:
          type: string
          description: The name of the process
      - purge_dups:
          type: string
          description: The name of the tool
      - 1.2.6:
          type: string
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - purge_dups:
          type: string
          description: The name of the tool
      - 1.2.6:
          type: string
          description: The expression to obtain the version of the tool
authors:
  - "@mahesh-panchal"
maintainers:
  - "@mahesh-panchal"
