name: "purgedups_purgedups"
description: Purge haplotigs and overlaps for an assembly
keywords:
  - Haplotype purging
  - Duplication purging
  - False duplications
  - Assembly curation
  - Read depth
tools:
  - "purgedups":
      description: "Purge_dups is a package used to purge haplotigs and overlaps in
        an assembly based on read depth"
      homepage: "https://github.com/dfguan/purge_dups"
      documentation: "https://github.com/dfguan/purge_dups"
      tool_dev_url: "https://github.com/dfguan/purge_dups"
      doi: "10.1093/bioinformatics/btaa025"
      licence: ["MIT"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - basecov:
        type: file
        description: A file containing a histogram of base coverage. Obtained from PURGEDUPS_PBCSTAT
        pattern: "*.PB.base.cov"
        ontologies: []
    - cutoff:
        type: file
        description: A file containing duplication cutoff points. Obtained from PURGEDUPS_CALCUTS
        pattern: "*.cutoffs"
        ontologies: []
    - paf:
        type: file
        description: A file of assembly alignments to itself
        pattern: "*.paf(.gz)?"
        ontologies: []
output:
  bed:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.dups.bed.gz":
          type: file
          description: A bed file of sequences purged of false duplications
          pattern: "*.bed.gz"
          ontologies: []
  log:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.purge_dups.log":
          type: file
          description: A log of the tool output
          pattern: "*.log"
          ontologies: []
  versions_purgedups:
    - - ${task.process}:
          type: string
          description: The name of the process
      - purge_dups:
          type: string
          description: The name of the tool
      - 1.2.6:
          type: string
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - purge_dups:
          type: string
          description: The name of the tool
      - 1.2.6:
          type: string
          description: The expression to obtain the version of the tool
authors:
  - "@mahesh-panchal"
maintainers:
  - "@mahesh-panchal"
