name: csvtk_mutate2
description: Create a new column from selected fields by awk-like arithmetic/string expressions
keywords:
  - mutate
  - tsv
  - csv
tools:
  - csvtk:
      description: A cross-platform, efficient, practical CSV/TSV toolkit
      homepage: http://bioinf.shenwei.me/csvtk
      documentation: http://bioinf.shenwei.me/csvtk
      tool_dev_url: https://github.com/shenwei356/csvtk
      licence: ["MIT"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input:
        type: file
        description: CSV/TSV formatted files, or files with a custom delimiter
        pattern: "*.{csv,tsv}"
        ontologies:
          - edam: http://edamontology.org/format_3752 # CSV
          - edam: http://edamontology.org/format_3475 # TSV
  - in_format:
      type: string
      description: Input format (csv, tsv, or a delimiting character)
      pattern: "*"
  - out_format:
      type: string
      description: Output format (csv, tsv, or a delimiting character)
      pattern: "*"
output:
  output:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.${out_extension}:
          type: file
          description: Mutated CSV/TSV file
          pattern: "*.{csv,tsv}"
          ontologies:
            - edam: http://edamontology.org/format_3752 # CSV
            - edam: http://edamontology.org/format_3475 # TSV
  versions_csvtk:
    - - ${task.process}:
          type: string
          description: The name of the process
      - csvtk:
          type: string
          description: The name of the tool
      - csvtk version | sed 's/.*v//g':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - csvtk:
          type: string
          description: The name of the tool
      - csvtk version | sed 's/.*v//g':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@fellen31"
maintainers:
  - "@fellen31"
