name: "fastawindows"
description: Quickly compute statistics over a fasta file in windows.
keywords:
  - genome
  - fasta
  - tsv
  - bed
tools:
  - "fastawindows":
      description: "fasta_windows is a tool written for Darwin Tree of Life chromosomal
        level genome assemblies. The executable takes a fasta formatted file and calculates
        some statistics of interest in windows"
      homepage: "https://github.com/tolkit/fasta_windows"
      licence: ["MIT"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: FASTA file
        pattern: "*.{fa,fasta,fna}"
        ontologies: []
output:
  freq:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - fw_out/*_freq_windows.tsv:
          type: file
          description: TSV file with frequencies and statistics
          pattern: "*.{tsv}"
          ontologies:
            - edam: http://edamontology.org/format_3475 # TSV
  mononuc:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - fw_out/*_mononuc_windows.tsv:
          type: file
          description: TSV file with mononucleotide counts
          pattern: "*.{tsv}"
          ontologies:
            - edam: http://edamontology.org/format_3475 # TSV
  dinuc:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - fw_out/*_dinuc_windows.tsv:
          type: file
          description: TSV file with dinucleotide counts
          pattern: "*.{tsv}"
          ontologies:
            - edam: http://edamontology.org/format_3475 # TSV
  trinuc:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - fw_out/*_trinuc_windows.tsv:
          type: file
          description: TSV file with trinucleotide counts
          pattern: "*.{tsv}"
          ontologies:
            - edam: http://edamontology.org/format_3475 # TSV
  tetranuc:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - fw_out/*_tetranuc_windows.tsv:
          type: file
          description: TSV file with tetranucleotide counts
          pattern: "*.{tsv}"
          ontologies:
            - edam: http://edamontology.org/format_3475 # TSV
  versions_fasta_windows:
    - - ${task.process}:
          type: string
          description: The name of the process
      - fasta_windows:
          type: string
          description: The name of the tool
      - fasta_windows --version | cut -d" " -f3:
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - fasta_windows:
          type: string
          description: The name of the tool
      - fasta_windows --version | cut -d" " -f3:
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@muffato"
maintainers:
  - "@muffato"
